replicaCount: 1

image:
  repository:
  tag:
  pullPolicy: IfNotPresent

services:
#  - type: LoadBalancer
#    suffix:
#    ports:
#      - protocol: TCP
#        port: 80
#        containerPort: 80

labels:

volumes:
#  - name: base-config
#    hostPath:
#      path: "/appdata/k3s/base"

volumeMounts:
#  - name: base-config
#    mountPath: "/config"


waitForServices:
#  - test-service

baseEnv:

env:

args:

configmaps:
