base:
  image:
    repository: postgres
    tag: 14.0
    pullPolicy: IfNotPresent

  services:
    - type: LoadBalancer
      ports:
        - protocol: TCP
          port: 5432
          containerPort: 5432

  env:
    - name: POSTGRES_DB
      value: tshows
    - name: POSTGRES_PASSWORD
      value: password
    - name: POSTGRES_USER
      value: postgres
