export { PersonInterface } from './person.interface';
export { GenderInterface } from './gender.interface';
export { GenreInterface } from './genre.interface';
export { KeywordInterface } from './keyword.interface';
export { StatusInterface } from './status.interface';
export { EpisodeInterface } from './episode.interface';
export { SeasonInterface } from './season.interface';
export { ShowDetailsInterface, PartialShowInterface } from './show.interface';
export { ProductionCompanyInterface } from './production-company.interface';
export { CastInterface } from './cast.interface';
export { CrewInterface } from './crew.interface';
export { CreditInterface } from './credit.interface';
